### ISSUE TITLE
Feature Request: Pardot Destination

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#1154]
Is your feature request related to a problem? Please describe.
Add [Pardot](pardot.com) as a destination for Grouparoo profiles and groups.

**Comment by bleonard** [comment]
There’s an unofficial node-pardot lib at [https://github.com/Datahero/node-pardot](https://github.com/Datahero/node-pardot) but doesn't seem to have much usage and is old. We’ll probably need to use the api directly.

**Using the api**



*   Base URL can change based on environment.
    *   Demos, developer orgs, and sandbox environments are hosted on the domain `pi.demo.pardot.com`.
    *   Training and production environments are hosted on the domain `pi.pardot.com`.
*   [https://developer.pardot.com/kb/authentication/](https://developer.pardot.com/kb/authentication/) requires creating a connected app

**Rate Limits**



*   Pardot Pro: 25,000 requests / day
*   Pardot Ultimate: 100,000 requests / day
*   Requests that exceed limits result in error code 122, resets beginning of next day
*   Can have up to 5 concurrent requests. >5 results in error code 66.

**API Versions**



*   V3 can only be used if "Allow Multiple Prospects with the Same Email Address" is disabled
*   V4 can only be used if "Allow Multiple Prospects with the Same Email Address" is enabled
*   V5 works for both and has a nicer API, but it only supports reading/querying prospect accounts and campaigns

v3/v4



*   Must pass `Pardot-Business-Unit-Id` header (obtained using Salesforce OAuth) to authenticate.
*   Defaults to returning XML. Change to json by using ?format=json

**Auth**



1. Use jsforce to get access_token - uses SOAP login api, so oauth stuff isnt needed
    1. Requires username, password, security key
    2. [https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_quickstart_login.htm](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_quickstart_login.htm) works! But it’s soap/xml :( 
2. Figure out salesforce SSO (oauth)
    3. Requires Connected App with pardot permission, client id, client secret, username, password, security key

Maybe it’s worth figuring out what jsforce does under the hood to see if we actually need the dependency or not. Will start off using jsforce to get the ball rolling.

**Profiles**

Map to “Prospects” in pardot



*   What is a prospect account? All its fields are configurable.
    *   Prospect accounts give you the ability to group prospects that work for the same company, keeping all the information about the company in one place.

[https://developer.pardot.com/kb/api-version-4/prospects/](https://developer.pardot.com/kb/api-version-4/prospects/) 

<span style="text-decoration:underline;">CREATE</span>


```
/api/prospect/version/4/do/create/email/<email>?...
```


/api/prospect/version/4/do/create/email/[new_prospect@pardot.com](mailto:new_prospect@pardot.com)?first_name=New&last_name=Prospect 

Email must be valid

<span style="text-decoration:underline;">UPDATE</span>

Can update by id or fid


```
/api/prospect/version/4/do/update/id/<id>
/api/prospect /version/4/do/update/fid/<fid>
```


/api/prospect/version/4/do/update/id/300?phone=888-123-4567

(all others are left unchanged)

**Can also be batched up to 50 prospects at a time:**

/api/prospect/version/4/do/batchCreate

/api/prospect/version/4/do/batchUpdate

/api/prospect/version/4/do/batchUpsert

Create


```
{
    "prospects": [
        {"email":"some@email.com","first_name":"First name","last_name":"Last name"},
        {"email":"some@email.com","first_name":"First name","last_name":"Last name"},
        {"email":"some@email.com","first_name":"First name","last_name":"Last name"}
    ]
}
```


Upsert


```
{
    "prospects": [
        {"email":"some@email.com","first_name":"First name","last_name":"Last name"},
        {"fid":"1234","first_name":"First name","last_name":"Last name"},
        {"id":"10","first_name":"First name","last_name":"Last name"}
    ]
}
```


If the request includes an email address but no ID or CRM FID, a prospect will be created with the email address.

Email list subscriptions can be modified while updating by using `list_&lt;list_id>=1` to create a subscription and `list_&lt;list_id>=0` to end a subscription. Subscribing to an already subscribed list is ignored. Same for unsubscribe.

<span style="text-decoration:underline;">DELETE</span>

By id or fid


```
/api/prospect/version/4/do/delete/id/<id>?...
/api/prospect/version/4/do/delete/fid/<fid>?..
```


Returns 204 no content on success

**Properties**

Supports a default set of fields, plus custom fields.

<span style="text-decoration:underline;">Built in fields</span>

[https://developer.pardot.com/kb/object-field-references/#prospect](https://developer.pardot.com/kb/object-field-references/#prospect)

<span style="text-decoration:underline;">Custom fields</span>

[https://developer.pardot.com/kb/api-version-4/custom-fields/](https://developer.pardot.com/kb/api-version-3/custom-fields/)

[https://developer.pardot.com/kb/object-field-references/#custom-field](https://developer.pardot.com/kb/object-field-references/#custom-field)



*   `/api/customField/version/4/do/query?...`
*   `/api/customField/version/4/do/create?`



<p id="gdcalert2" ><span style="color: red; font-weight: bold">>>>>>  gd2md-html alert: inline image link here (to images/image2.png). Store image on your image server and adjust path/filename/extension if necessary. </span><br>(<a href="#">Back to top</a>)(<a href="#gdcalert3">Next alert</a>)<br><span style="color: red; font-weight: bold">>>>>> </span></p>


![alt_text](images/image2.png "image_tooltip")


**Groups**

Email List subscription, Tags, Campaign? Seems like we’re looking for lists.

<span style="text-decoration:underline;">List </span>

[https://developer.pardot.com/kb/api-version-3/lists/#using-lists](https://developer.pardot.com/kb/api-version-3/lists/#using-lists) 

[https://developer.pardot.com/kb/api-version-3/list-memberships/#using-list-memberships](https://developer.pardot.com/kb/api-version-3/list-memberships/#using-list-memberships)

In the UI, this is under Marketing > Segmentation > Lists

They can be static or dynamic (ours would be static)

<span style="text-decoration:underline;">Tags</span>

Simpler, can be used for multiple things, not just prospects. Doesn’t seem like they can be added to prospects through the api.

<span style="text-decoration:underline;">Campaign</span>

Prospects are only associated with one Pardot campaign. They have one campaign_id assigned to them as a field on the prospect.

You can create/update campaign info through the api:

[https://developer.pardot.com/kb/api-version-3/campaigns/](https://developer.pardot.com/kb/api-version-3/campaigns/)
