### ISSUE TITLE
Typo in getting started instructions

### ISSUE THREAD

**Issue by spicypenguin** [grouparoo/grouparoo#1346]
The instructions on the getting started guide have a typo.

Page in question: https://www.grouparoo.com/docs/getting-started

Instructions state to run `npm grouparoo install -g` but required command is `npm install -g grouparoo`?

**Comment by evantahler** [comment]
Thank you so much for pointing that out!  I'll get that fixed ASAP (via https://github.com/grouparoo/www.grouparoo.com/pull/251)
