### ISSUE TITLE
Add support for different kinds of entities within Grouparoo

### ISSUE THREAD

**Issue by spicypenguin** [grouparoo/grouparoo#1348]
Grouparoo currently assumes that the thing that is being tracked in the system is exclusively "profiles" or "people", who will be eventually merged down to a single entity profile (e.g. anonymous users linking into a known user profile).

It would be great if you could model different parts of a business domain as independent profiles, that could have a relationship with each other. For example, you could have user profiles, which could be joined to account profiles.

Group membership should be able to take advantage of these relationships (e.g. select all users who belong to an account with a property of value X).

**Comment by andyjih** [comment]
Hi @spicypenguin, and thank you for the feedback! 

We totally hear you, and adding something akin to an Account object is a capability we're planning on building. We have issue #653 tracked here in our [Roadmap](https://github.com/orgs/grouparoo/projects/26). I'll go ahead an close this issue, and do feel free to add additional comments or thoughts in that issue.
