### ISSUE TITLE
Improved documentation on how to use Event app/source/properties

### ISSUE THREAD

**Issue by spicypenguin** [grouparoo/grouparoo#1349]
I poked around trying to get event sources working, but the documentation related to event sourcing is fairly limited. There wasn't any clear documentation on how to generate an API key, which I figured out through trial and error but it would be great if there was clearer documentation on a source-by-source basis of how to setup and configure each available source.

For example, if I wanted to forward events to Grouparoo from a 3rd party (vs. using your client library) I can only understand how to do this by reverse engineering the web-client package and finding the API end point.

**Comment by andyjih** [comment]
Great point! That portion of our docs deserves an update, and we'll get to that shortly. Thank you!

**Comment by bleonard** [comment]
Jut cleaning some things up, here. We actually have removed the client library to focus just on the data warehouse use cases. If you have events in your data store and want to sync them to destinations, we'd love to chat @spicypenguin but I'm closing this issue about that library.
