### ISSUE TITLE
Error: "Cannot find a 'mysql-table-import' plugin"

### ISSUE THREAD

**Issue by coquej** [grouparoo/grouparoo#1536]
**Describe the bug**
Showing error "mysql-table-import missing plugin". I don't know how to install it and why should I have to install it, as I've already installed @grouparoo/mysql plugin...

**To Reproduce**
1. Created MySQL app
2. Created MySQL source (table)
3. Went to UI, Sources tab.
4. Error message: "Cannot find a "mysql-table-import" plugin. Did you install it?"

**Expected behavior**
I expected to see the Source already created in the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/43119642/112638439-8cb9c200-8e3f-11eb-986c-832ebfd7298b.png)

**Environment:**
 - Node.js Version [0.2.6, node version 15.11.0]

Attached, source javascript code:
[mysql_source.txt](https://github.com/grouparoo/grouparoo/files/6212111/mysql_source.txt)

**Comment by evantahler** [comment]
Hi @coquej! I'm sorry to hear that you are having trouble.   Can you please share your `package.json`?

**Comment by coquej** [comment]
[package_json.txt](https://github.com/grouparoo/grouparoo/files/6213088/package_json.txt)

**Comment by evantahler** [comment]
Thanks for sharing everything!

I've tried out your `package.json` and source locally, and looks OK to me.  Can you confirm that NPM really did install the relevant Grouparoo packages?  eg:

```
$ ls -la node_modules/@grouparoo

drwxr-xr-x    8 evan  wheel    256 Mar 26 12:12 .
drwxr-xr-x  745 evan  wheel  23840 Mar 26 12:13 ..
drwxr-xr-x   12 evan  wheel    384 Mar 26 12:12 app-templates
drwxr-xr-x   12 evan  wheel    384 Mar 26 12:12 client-web
drwxr-xr-x   17 evan  wheel    544 Mar 26 12:12 core
drwxr-xr-x   12 evan  wheel    384 Mar 26 12:12 mailchimp
drwxr-xr-x   12 evan  wheel    384 Mar 26 12:12 mysql
drwxr-xr-x   14 evan  wheel    448 Mar 26 12:12 ui-community
```

If you don't see the mysql package in `node_modules/@grouparoo`, try `npm install`. 

---

**`package.json`**: 

```json
{
  "author": "Grouparoo Inc <hello@grouparoo.com>",
  "name": "@grouparoo/app-example",
  "description": "An example Grouparoo Deployment",
  "version": "0.0.1",
  "license": "MPL-2.0",
  "private": true,
  "engines": {
    "node": ">=12.0.0 <16.0.0"
  },
  "dependencies": {
    "@grouparoo/core": "0.2.6",
    "@grouparoo/mailchimp": "0.2.6",
    "@grouparoo/mysql": "0.2.6",
    "@grouparoo/ui-community": "0.2.6"
  },
  "scripts": {
    "start": "cd node_modules/@grouparoo/core && ./bin/start"
  },
  "grouparoo": {
    "plugins": [
      "@grouparoo/mailchimp",
      "@grouparoo/mysql",
      "@grouparoo/ui-community"
    ]
  }
}
```

**Comment by coquej** [comment]
I am seeing the same as you:

![image](https://user-images.githubusercontent.com/43119642/112684462-5eee7080-8e73-11eb-86a4-45cefb2eb345.png)

**Comment by coquej** [comment]
Hey! I deleted the project directory and created it again (copying the old config folder), and now is working! 
Apologies for the wasted time 😅. The typical IT solution worked as always...
