### ISSUE TITLE
 Cannot find a "csv-import" plugin

### ISSUE THREAD

**Issue by matt-fellows** [grouparoo/grouparoo#1661]
**Describe the bug**
Validate message when trying to validate a new CSV source: 

> warning: [ config ] error with source `leads` (leads): Cannot find a "csv-import" plugin.  Did you install it? 

**To Reproduce**
1. grouparoo generate  csv:source:local leads -p csv_app
2. grouparoo validate 

**Expected behavior**
Have tried a number of things: 
1.  `npm i csv-import`
2. `grouparoo install csv-import`
3. `npm i csv`
4. `npm i csv-parser`
5. `npm i`

Not sure what `csv-import` the error is referring to here. 

**Environment (please complete the following information):**
 - OS:  OSX
 - Grouparoo Version 0.2.12
 - Node.js Version v14.16.0

**Additional context**
My package.json lists these plugins: 
`"plugins": [
      "@grouparoo/csv",
      "@grouparoo/files-local",
      "@grouparoo/marketo",
      "@grouparoo/ui-community"
    ]`

**Comment by pedroslopez** [comment]
Hi Matt! Sorry you're having trouble. It seems like there's a bug in our generator templates. 

Please try setting the `type` to `csv-file-import` in your configuration file, like so:
```js
{
      class: "source",
      id: "leads",
      name: "leads",
      type: "csv-file-import",
      appId: "csv_app",
...
```

I've opened up a PR to fix this in our templates #1663

**Comment by bleonard** [comment]
```
roo generate csv:app csv_app
roo generate csv:remote:source leads --parent csv_app
```

Note, you will need the app and the source. Then, because of the bug you'll have to change it to `"csv-remote-import"`
I assume you want that one instead of `"csv-file-import"` because `"csv-file-import"` is actually in our s3 store.  Below are the files it will make.

Note you'll need to fill out the`url`. Right not only remote urls are accepted, though it would be an interesting case to handle local files. What's the use case you have?

Then we can make properties from that CSV. Maybe I'll make a full example for you.


/apps/csv_app.js
```
exports.default = async function buildConfig() {
  return [
    {
      class: "app",
      id: "csv_app",
      name: "csv_app",
      type: "csv",
    },
  ];
};
```

/sources/leads.js
```
exports.default = async function buildConfig() {
  return [
    /**
     * --------------------
     * Source
     * --------------------
     */
    {
      class: "source",
      id: "leads",
      name: "leads",
      type: "csv-remote-import",
      appId: "csv_app", // Set this value to the ID of the App this Source uses - e.g. `appId: "csv_app"`
      options: {
        url: "...", // The URL of a publicly available CSV file - e.g. `url: "https://example.com/data.csv"`
        fileAgeHours: 1, // The number of hours to cache a download of the remote CSV file before downloading it again and checking for changes.
      },

      /**
       * A list of mappings for this source as:
       *
       *     "csv_column": "grouparoo_property_id"
       *
       * For example, if your CSV files has an `id` column, and you want to map that to the
       * `user_id` property in this Grouparoo source, your mapping would look like:
       *
       *     mapping: { id: "user_id" }
       *
       * If this is the first Source in Grouparoo, you'll want to create a property in the
       * bootstrappedProperty section below. Otherwise, you can create properties with the Grouparoo
       * CLI.
       */
      mapping: {
        id: "userId",
      },

      /**
       * If this is the first Source in Grouparoo, you must bootstrap it with an initial property.
       * To do so, uncomment the lines below and fill in the appropriate values. Otherwise, you can
       * create properties with the Grouparoo CLI.
       */
      // bootstrappedProperty: {
      //   id: "user_id",
      //   name: "User Id",
      //   type: "integer",
      //   options: {
      //     column: "id",
      //   },
      // },
    },

    /**
     * ---------------
     * Schedule
     * ---------------
     *
     * A Schedule tells Grouparoo how frequently to check the Source for updated
     * data and import it into the application database. If you would like to
     * set a Schedule for this Source, uncomment the following section.
     */
    // {
    //   id: "leads_schedule",
    //   name: "leads_schedule",
    //   class: "schedule",
    //   sourceId: "leads", // The ID of the Source this Schedule uses
    //   recurring: true, // should this Schedule regularly run?
    //   recurringFrequency: 1000 * 60 * 15, // 15 minutes, in ms
    // },
  ];
};
```

**Comment by bleonard** [comment]
I made this sample project to show how to pull in more info from remote CSVs.
It has example of properties. Right now, we only support "exact" values in properties. That is, there is a column called `user_id` with the value that should be in Grouparoo.

https://github.com/grouparoo/app-example-csv

**Comment by matt-fellows** [comment]
Thanks so much for the example; it worked like a charm. 

I'm using `http-server` to serve up a local CVS file until I can finalize the remote server details that'll be providing the file/data I'll be piping through Grouparoo. Any use cases I have for local file support seem handled by using a local server. 

Thanks so much for the help!
