### ISSUE TITLE
Destination: Mixpanel

### ISSUE THREAD

**Issue by bleonard** [grouparoo/grouparoo#1690]
Looks like we would use their Profile API to set properties: https://developer.mixpanel.com/reference/user-profiles#profile-set
Library details here: https://developer.mixpanel.com/docs/nodejs

It looks like they have a concept of groups that profiles can belong to. But this is more like a list of companies.
Segment [sets](https://segment.com/docs/connections/destinations/catalog/mixpanel/) groups as profile properties with boolean.

**Comment by evantahler** [comment]
Closed by https://github.com/grouparoo/grouparoo/pull/2082, https://github.com/grouparoo/grouparoo/pull/2137, and https://github.com/grouparoo/grouparoo/pull/2189
