### ISSUE TITLE
Feature Request: Ability to add custom code to our property configs

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#1721]
Some users have asked for the ability to add custom code to property definitions. For example being able to write a function that takes a part of a user_id and mapping that to a specific property value.

**Comment by evantahler** [comment]
Possibly a duplicate of https://github.com/grouparoo/grouparoo/issues/780

**Comment by evantahler** [comment]
Closed by https://github.com/grouparoo/grouparoo/pull/2146
