### ISSUE TITLE
"grouparoo init" command stalls

### ISSUE THREAD

**Issue by doctor-spaceman** [grouparoo/grouparoo#1979]
**Describe the bug**
When using "grouparoo init", the process stalls and gives an error.

**To Reproduce**
1. Install grouparoo
2. Execute grouparoo init
3. Observe "Could not install" error

**Expected behavior**
A new Grouparoo project setup is completed

**Stack Trace**
```
C:\Users\Matt\Dev\grouparoo-test (master -> origin)
λ grouparoo init .
�  Generating new Grouparoo Project

i path: C:\Users\Matt\Dev\grouparoo-test
‼ package.json already exists, not modifying
‼ .env already exists, not modifying
‼ .gitignore already exists, not modifying
√ Created directories for config objects.
× Could not install:
npm ERR! code 1
npm ERR! path C:\Users\Matt\Dev\grouparoo-test\node_modules\@grouparoo\core
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run thank-you
npm ERR! > @grouparoo/core@0.3.3 thank-you
npm ERR! > ./thank-you
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matt\AppData\Local\npm-cache\_logs\2021-06-21T23_21_49_660Z-debug.log
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Grouparoo Version: 0.3.3
 - Node.js Version: 14.6.0

**Additional context**
User is prevented from moving forward with the Grouparoo installation.  The error occurs regardless of whether using "init" on the current directory or not.

**Comment by evantahler** [comment]
Hello @doctor-spaceman!  

I'm sorry to say that at the moment, Grouparoo doesn't support Windows (directly).  There is some more information here https://github.com/grouparoo/grouparoo/discussions/1491.

At the moment the best option is probably to use the Windows Subsystem for Linux (WSL) to run Grouparoo within Ubuntu on Windows

**Comment by doctor-spaceman** [comment]
Thanks @evantahler!
