### ISSUE TITLE
When a schedule is invalid (recurring-true but minutes=0) the schedule should not be saved

### ISSUE THREAD

**Issue by evantahler** [grouparoo/grouparoo#211]

**Comment by andyjih** [comment]
Repro steps:
1. Create a new schedule
2. Check 'recurring' and leave the frequency to `0`
3. Click Update
4. See appropriate error that frequency can't be `0`
5. Update frequency to a valid number
6. Click Update
7. Still see an error saying that the frequency can't be `0`.
