### ISSUE TITLE
Feature Request: Mailjet as a destination

### ISSUE THREAD

**Issue by johndbritton** [grouparoo/grouparoo#2148]
https://www.mailjet.com/feature/segmentation/

**Comment by bleonard** [comment]
Looks like mailjet has a Contacts [model](https://dev.mailjet.com/email/reference/contacts/contact/) that we would sync with. The email is the primary key.
Then each contact has [properties](https://dev.mailjet.com/email/reference/contacts/contact-properties/). This links speaks to `/contactdata` to add additional properties.

Overall, this [guide](https://dev.mailjet.com/email/guides/contact-management/#manage-contact-properties) seems to be the best. It suggests that you have to make the properties ahead of time for extra contact data. Then we'd map to them.

There is info on the same [page](https://dev.mailjet.com/email/guides/contact-management/#add-a-contact-to-a-contact-list) on how to add to a contact list. It looks one at a time.

**Comment by evantahler** [comment]
This destination will be added in #2202

**Comment by boardfish** [comment]
Thanks for delivering on this so quickly for us! Looking forward to getting this working within our system.
