### ISSUE TITLE
The cluster-name setting on a new db shouldn't cause a crash

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#2273]
If you have a cluster-name setting config file on a brand new db such as: 

```
{
  "id": "cluster-name",
  "class": "Setting",
  "pluginName": "core",
  "key": "cluster-name",
  "value": "New Cluster"
}
```

the app crashes. It shouldn't crash!

**Comment by bleonard** [comment]
Fixed in 0.6.2 release https://github.com/grouparoo/grouparoo/releases/tag/v0.6.2
