### ISSUE TITLE
Feature Request: Clickhouse Source

### ISSUE THREAD

**Issue by chrisgoddard** [grouparoo/grouparoo#2337]
Any plans to support Clickhouse as a data source or destination?

**Comment by andyjih** [comment]
Hi @chrisgoddard! It's on our radar, but no concrete plans at the moment. Is Clickhouse as a source a blocker to you using Grouparoo? Let us know and we can adjust our prioritization. Thanks!

**Comment by spatialy** [comment]
Hi @andyjih ... ClickHouse is an interesting option to have, for example we mostly deploy ClickHouse to our clients due the benefits (mainly cost and isolation for security)

**Comment by andyjih** [comment]
Hi @spatialy ! Thanks for letting us know!

**Comment by evantahler** [comment]
Closed by https://github.com/grouparoo/grouparoo/pull/2467

**Comment by bleonard** [comment]
@chrisgoddard @spatialy This is now in our 0.7.4 release!

**Comment by spatialy** [comment]
great!
