### ISSUE TITLE
Can't add a new app

### ISSUE THREAD

**Issue by NigelKibodeaux** [grouparoo/grouparoo#2391]
**Describe the bug**
I'm not sure if this is just outdated documentation or a problem with the app, but I can't figure out how to add an app.

After a fresh `npm install`, I'm going through setup. I'm on http://localhost:3000/setup and I see what's in the first screenshot. I click "[Learn More](https://www.grouparoo.com/docs/config/apps)" to learn how to install an app and the screenshots look like the second image. There is no "Apps" link in the sidebar.

I find "Apps" under the "Platform" menu and click it (see third screenshot) but don't get the button to add an app like is shown in the documentation.

**Expected behavior**
From the documentation, I expected to see a button to add an app.

**Screenshots**
![image](https://user-images.githubusercontent.com/408692/135934316-1954a727-f51b-4d5e-be3b-e63909fe2bc2.png)
![image](https://www.grouparoo.com/_next/image?url=%2Fimages%2Fdocs%2Fguides%2Fconfig%2Fapp--01-add.png&w=1080&q=75)
![image](https://user-images.githubusercontent.com/408692/135938059-8775274a-9f8e-4bba-b09e-4c95456e8932.png)

**Environment (please complete the following information):**
 - OS: OSX
 - Browser: Safari
 - Grouparoo Version: 0.0.1
 - Node.js Version: 14.8.0

**Comment by andyjih** [comment]
Hi @NigelKibodeaux! Thank you for reporting this issue! 

As you're running the Community edition of Grouparoo, you will configure Grouparoo using code. Here is a link to the specific section of our docs that can help you with configuring Grouparoo: https://www.grouparoo.com/docs/config/code-config

The specific doc for generating and configuring an app is this doc: https://www.grouparoo.com/docs/config/code-config/apps

I'll create an issue as well for us to improve our docs navigation as this section is a bit buried at the moment. 

If you run into any other issues or have other questions, please feel free to create another issue. Thanks!

**Comment by bleonard** [comment]
@NigelKibodeaux you do need to use code to configure Grouparoo, but that screenshot you put is in the UI that helps you. It says it in the doc, but it's probably too small.  

The (green boxed in the screenshot) link goes to here: https://www.grouparoo.com/docs/config
It more or less says to run `grouparoo config` to bring up the UI with ability to create Apps and save them to your project (to then check into git, etc).

<img width="1142" alt="Screen Shot 2021-10-04 at 5 44 12 PM" src="https://user-images.githubusercontent.com/36106/135943117-298ce13b-88c0-4b12-8afb-d3dd7097d1d4.png">

**Comment by NigelKibodeaux** [comment]
Thank you! I totally missed that UI Config line.
