### ISSUE TITLE
[Feature]: Add Airtable as a Destination 

### ISSUE THREAD

**Issue by brandon-segal** [grouparoo/grouparoo#2551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Add Airtable bases and tables as destinations to Grouparoo

### Describe the solution you'd like.

An Airtable plugin maintained by Grouparoo that allows users to sync arbitrary data from sources to Airtable tables

### Describe an alternate solution.

Alternatives to a grouparoo maintained solution would be one maintained by an external contributor/ a plugin in a seperate repository

### Additional context

This is currently being used as a solution with our team since the team we are interfacing with already has all of their data in Airtable and wants to incorporate data from our data warehouse.

**Comment by bleonard** [comment]
This is a great idea, @brandon-segal.

Everything is pretty clear when we think about the [steps for developing a destination](https://www.grouparoo.com/docs/development/destinations). There are [APIs](https://airtable.com/api/meta) to get the bases, tables, and fields. 

A user would probably pick the base in the app options and the table in the destination options.
There would be a required input as to which fields is the primary key.

Then we could map to any of the fields, leaving off the ones that are computed by formulas, etc.

The only slightly tricky thing looks to be finding if the record is already in the table. I'm assuming people have big enough tables that it's wrong to iterate through all the records looking for a match. [This](https://community.airtable.com/t/how-to-search-for-specific-value-through-api-filterbyformula/21271) suggests we can use `filterByFormula`. 

The other decision to make would be if we would use our batch approach or single. The API notes I saw said it could make 10 at a time. That's not high but it's something. My guess is the decision will come down the the `filterByFormula` -- can we reliably pass in 10 (or 100) values in there to get the results of? Maybe with `OR()` or `=ANY[]` approaches.

**Comment by bleonard** [comment]
I would look into the `hubspot-export-objects` Destination that we recently did. There are a lot of parallels.
* The app takes an API key as an option
* The `destinationOptions` has you pick a schema and a primary key
* The `destinationMappingOptions` includes the primary key and any required fields.
* `exportRecords` does batching using a helper and there are some weird requirements with search.

https://github.com/grouparoo/grouparoo/blob/main/plugins/@grouparoo/hubspot/src/initializers/plugin.ts
I'd call it `airtable-export-records`.

**Comment by bleonard** [comment]
Added in https://github.com/grouparoo/grouparoo/pull/2716 for release in v0.8.0
