### ISSUE TITLE
[Feature]: --verbose exports flag

### ISSUE THREAD

**Issue by nyccto** [grouparoo/grouparoo#2650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

`--verbose exports` or similar flag to show information for 

- all fields sent to destination
- the primary key (instead of or in addition to the grouparoo internal id)
- type of operation e.g. created/updated/deleted for each record

Bonus: if we can have a log file generated in addition to the console output e.g. `--verbose exports --log /tmp/grouparoo-super-awesome.log`

### Describe the solution you'd like.

add `--verbose exports` flag

**Comment by bleonard** [comment]
Here's what we are thinking @nyccto 

You would set an env variable (GROUPAROO_EXPORT_LOG=/path/to/file.json) then log this:

Each line in the file is stringified json of:
* state (complete|failed)
* grouparoo record id
* grouparoo model id
* new groups
* new properties
* destination id

The reason for stringified JSON is so you can parse this or send it to a log aggregator (splunk, etc)
Does that solve your issue? In either case, I'm curious about the _why_ here.

**Comment by nyccto** [comment]
That would work. The _why_ is for troubleshooting / tracking point in time values and failures. We are using ephemeral storage so the logs could be exported before the pipeline instances are terminated.
