### ISSUE TITLE
[Bug]: Update Getting Started documentation for Development for MacOS

### ISSUE THREAD

**Issue by asdfryan** [grouparoo/grouparoo#2842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I ran through the Getting Started > Running the Monorepo documentation on MacOS and it didn't work out of the box for me. Specifically, I went through the Docker flow (Option 2).

<img width="1769" alt="Screen Shot 2022-01-20 at 4 36 50 PM" src="https://user-images.githubusercontent.com/1498449/150444584-97f53fa2-9ebe-4760-90e1-9153cf5d8c82.png">

Specifically, it seems that there needs to be an additional step to add your username as a role (with LOGIN permissions).

Here's how I worked around it:
```
docker exec -ti <CONTAINER_ID> psql -U postgres postgres
psql (14.1 (Debian 14.1-1.pgdg110+1))
Type "help" for help.

postgres=# CREATE ROLE <USERNAME> superuser;

postgres=# ALTER ROLE <USERNAME> WITH LOGIN;
```

### Expected Behavior

App should work out of the box.

### Stack Trace

```markdown
asdfryan@Ryans-MacBook-Pro staging-enterprise % npm run dev

> @grouparoo/app-staging-enterprise@0.8.0-alpha.8 dev
> cd node_modules/@grouparoo/core && ./bin/dev

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/* ../plugins/**/*.js
[nodemon] watching extensions: js,jsx,ts,tsx
[nodemon] starting `node_modules/.bin/ts-node --transpile-only --log-error src/grouparoo.ts`
2022-01-20T23:30:26.362Z - notice: Starting Grouparoo v0.8.0-alpha.8 on node.js v16.13.1 
2022-01-20T23:30:33.055Z - notice: Modified your runtime environment with /Users/asdfryan/supergrain/supergrain/grouparoo/apps/staging-enterprise/.env 
2022-01-20T23:30:34.359Z - error: Error from Initializer name=sequelize file=/Users/asdfryan/supergrain/supergrain/grouparoo/node_modules/.pnpm/ah-sequelize-plugin@5.1.1_f29751961d501bdbc450ca676b95fe81/node_modules/ah-sequelize-plugin/dist/initializers/sequelize.js type=initialize stack=role "asdfryan" does not exist 
[nodemon] app crashed - waiting for file changes before starting...
```

### Environment

* OS: MacOS
* Browser: N/A
* Grouparoo Version: Head as of issue creation
* Node.js Version: v16.13.1

**Comment by evantahler** [comment]
Thanks for the awesome bug report! I'll update the docs shortly, but you can use the `$USER` variable in bash or zsh to pass your current username to the POSTGRES_USER environment variable.  That's probably the best way to set up the container.

so the new command is:

```
docker run -d --rm --name grouparoo-postgres -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=grouparoo_development -e POSTGRES_USER=$USER postgres
```

**Comment by asdfryan** [comment]
Ah, that makes sense. Thanks!
