### ISSUE TITLE
Hide the navigation scroll bar unless it's needed

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#315]
Right now the scroll bar shows up if the user is using a physical mouse with a physical scroll wheel. We should hide the scroll bar unless the div is too short.

or: restyle the Grouparoo scroll bar to be light-blue, then that would be fine too.

**Comment by evantahler** [comment]
Here is some more detail on this https://muffinresearch.co.uk/osx-remove-scrollbars-that-appear-when-using-a-mouse/ and https://stackoverflow.com/questions/44668257/different-looks-on-scrollbars-when-using-usb-mouse-vs-wireless-trackpad-in-os-x

**Comment by evantahler** [comment]
This seems to be the most complete refrence https://css-tricks.com/almanac/properties/s/scrollbar/
