### ISSUE TITLE
When importing a profile, if a profile property rule (A) definition depends on another profile property rule (B), import the dependency profile property rule (B) first.

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#354]
Example:

```sql
SELECT gender 
FROM `bigquery-public-data.usa_names.usa_1910_current` 
WHERE LOWER(name) = LOWER('{{ firstName }}') 
GROUP BY gender 
ORDER BY SUM(number) DESC
```

We need to be sure that `{{ firstName }}` is updated before trying load in `gender`

**Comment by andyjih** [comment]
Validate that you can't get a circular dependency

**Comment by evantahler** [comment]
Thoughts: 
* If we truly try to sort the order of profile property imports, we are going to move away from the pattern of importing a source at a time... which in turn means that the notion of importing many profile properties in a 'batch' goes away.
  * Or, do we not allow sources to reference variables within the same source?  That seems wrong.
* Could this be handled more simply by just importing twice (or as many times as the dependency chain is deep)?

Determining order is a multi-step process
  1) import any properties that have no external dependencies (`userId`)
  2) import any properties that any source uses in a mapping (`userId`)
  3) import any properties that other properties reference with mustache
  4) import all remaining properties

**Comment by andyjih** [comment]
Importing 2x or more feels inefficient.

If we go down the path of determining order in that multi-step process, we also need to not start the next step until the previous step has completed right? That seems like the "right" approach, but not sure what implications might arise. cc @bleonard
