### ISSUE TITLE
Autocomplete dropdown list in Postgres Destination shows more columns than expected

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#363]
I set up a new postgres destination. The columns that showed up in the edit tab weren't of the table that I selected. Or maybe they were all of the columns across every table?

**Comment by andyjih** [comment]
![Screen Shot 2020-06-16 at 2 53 52 PM](https://user-images.githubusercontent.com/633226/84832200-b0fb8f00-afe1-11ea-9428-da6636f58582.png)

**Comment by evantahler** [comment]
More color on this:  At the moment, we don't have conditional choices for these settings (ie: one selection doesn't influence the other options) so all possible options for all possible permutations are being pre-loaded by the plugin.  

The solution is to keep going back to the plugin with the selected options and getting the next set of options.  There's also likely a new input type called `pending` which shows on the page, but isn't modifiable until some later state when it changes to `list` or `autocomplete`.  "PrimaryKey" would be an example of this, before "Table" is chosen

**Comment by andyjih** [comment]
Got it. I think a `pending` input type makes sense to me since it's dependent on previous inputs.

**Comment by evantahler** [comment]
@andyjih you got it! 


![output](https://user-images.githubusercontent.com/303226/84958753-e4f2b500-b0b2-11ea-9164-a1cdfc42cd74.gif)
