### ISSUE TITLE
Feature Request: SendGrid Destination

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#367]

**Comment by johndbritton** [comment]
@evantahler @bleonard Was this implemented? I can't find a reference in the docs or in the code.

**Comment by bleonard** [comment]
We have not implemented this one yet.

This was a way were were logging feature requests and putting them on our [roadmap](https://www.grouparoo.com/roadmap).

I would suggest trying out Mailchimp. It might work better to separate your transactional and marketing emails anyway.

**Comment by bleonard** [comment]
Reopening to put on current roadmap.

**Comment by bleonard** [comment]
SendGrid is a transactional email service but also has a CRM.

https://sendgrid.com/docs/api-reference/

Notably, the “new API” (Contacts/Lists) is job based and seemingly not as a good of fits as the “Legacy API” (Recipients/Lists).

**<span style="text-decoration:underline;">Profiles</span>**

PUT https://api.sendgrid.com/v3/marketing/contacts

The API has [Contacts](https://sendgrid.com/docs/api-reference/). Email address is required.

One nuance here from other endpoints that we have been working with is that it is asynchronous. You submit the contacts, get a “job_id” and check back later to see how it went.

GET https://api.sendgrid.com/v3/marketing/contacts/imports/{job_id}

We can check the job status given the “job_id” but it doesn’t have the answer per record. If we do it one record at a time, I guess that would work out.

POST https://api.sendgrid.com/v3/marketing/contacts/search

It says if you really want to see if it worked, you should use search. Note this only returns 50 records at a time. In either case, this would be used in the “do they already exist” checks, especially when changing email addresses.

**<span style="text-decoration:underline;">Profile Properties</span>**

POST https://api.sendgrid.com/v3/marketing/field_definitions

Sendgrid has the notion of custom fields. So this list will exist to be mapped to Grouparoo properties. There’s no mention of how to set the users ones, but it’s pretty likely it’s via the contacts API

**<span style="text-decoration:underline;">Groups</span>**

Sendgrid has Lists with different endpoints to create, add, and remove. Overall, this is like the Hubspot API.

GET /marketing/lists

We will need to look them up by name and there is not an endpoint for that. So we can get 1000 at a time.

POST /marketing/lists

How to create

DELETE /marketing/lists/{lsit_id}/contacts

Passing in who to remove. This also creates a background job.

The [documentation](https://sendgrid.com/docs/api-reference/) doesn’t actually have adding via API, but the legacy does. Maybe an omission?

**<span style="text-decoration:underline;">Library</span>**

[https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/client/USAGE.md](https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/client/USAGE.md)

This is a somewhat generic library supported by SendGrid.

Notably, it doesn’t reference the new API. Maybe it’s better to use the recipients/list approach.
