### ISSUE TITLE
Feature Request: Onboarding experience

### ISSUE THREAD

**Issue by bleonard** [grouparoo/grouparoo#657]
**Is your feature request related to a problem? Please describe.**
It would be nice if the first-time user was more clearly led down the path of setting up Grouparoo.

**Describe the solution you'd like**
We've made plenty of documentation about how things work. Let's link that.
There are clear steps to begin. 
- Adding an app for your first source
- creating the source
- configuring that source to pull in your core "user" object
- making sure there are unique keys for these new profiles

**Comment by evantahler** [comment]
closed by https://github.com/grouparoo/grouparoo/pull/715 and related features.
