### ISSUE TITLE
Postgres Source SSL Support

### ISSUE THREAD

**Issue by alastairstuart** [grouparoo/grouparoo#734]
**Is your feature request related to a problem? Please describe.**
Postgres sources are often only connectable via an SSL secured connection. Currently grouparoo does not appear to support such connections:

**Describe the solution you'd like**
Add an 'ssl' boolean to the pg module's appOptions to enable SSL connections.

**Describe alternatives you've considered**
SSL tunnels (inefficient)

**Additional context**
N/A

**Comment by evantahler** [comment]
Thanks @alastairstuart!

We use https://node-postgres.com under the hood for our Postgres connections, and *think* that it will actually try to connect to SSL by default, if your Postgres server supports it 

From https://node-postgres.com/features/ssl:
> node-postgres supports TLS/SSL connections to your PostgreSQL server as long as the server is configured to support it. When instantiating a pool or a client you can provide an ssl property on the config object and it will be passed to the constructor for the node TLSSocket.

That said, we don't yet bubble up the `ssl` options to provide a custom SSL cert/key/ca if you need to provide those.  Is that what you are looking for?

**Comment by alastairstuart** [comment]
Support client certificates would be great - but I think setting ssl to true may be sufficient - see https://stackoverflow.com/questions/22301722/ssl-for-postgresql-connection-nodejs

**Comment by evantahler** [comment]
It turns out that it was a little bit wackier than just adding `ssl=true`.  I've added the options for SSL connections and added a little walkthough in #735!
