### ISSUE TITLE
Create a Source asks to create an app

### ISSUE THREAD

**Issue by scottybo** [grouparoo/grouparoo#737]
**Describe the bug**
I added Mailchimp as an app, and then went to Create a source and I get shown this message:

![image](https://user-images.githubusercontent.com/11498904/93191682-ba110f00-f73c-11ea-84a9-7c2b6d8e842e.png)

**To Reproduce**
1.  Fresh install via npx / npm
2. Connect Mailchimp
3. Choose to add a source

**Expected behavior**
I should have been able to create a source

**Screenshots**
![image](https://user-images.githubusercontent.com/11498904/93192076-2f7cdf80-f73d-11ea-9c2e-9ba0d009e231.png)

**Stack Trace**
If applicable, add the full stack trace you see along with the error.

**Environment (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Grouparoo Version: @grouparoo/core@0.1.13
 - Node.js Version: 

**Additional context**
N/A

**Comment by evantahler** [comment]
Thank you for trying Grouparoo @scottybo!  

At the moment, Mailchimp is an App that can only be used as a Destination (ie: Grouparoo -> Mailchimp).  To create a Source, you'll need to make an App that can be used as a Source (ie: Source -> Grouparoo).  Options include Google Sheets, Postgres, MySQL, etc.  

We can certainly make the language around this more clear.  I'll leave this issue open until we do.

**Comment by evantahler** [comment]
Hopefully, I've added some clarity via #738

**Comment by andyjih** [comment]
@scottybo Hi there! I have a follow-up question for you if you don't mind: it looks like you wanted to use Mailchimp as a Source. Can you share some detail on what data you are hoping to important from Mailchimp into Grouparoo and what you are hoping to do with that data? It would be great to learn more about your use case to inform our roadmap. Thanks!

**Comment by scottybo** [comment]
Thanks for such a speedy response everyone!

@andyjih I'm still new to Grouparoo, so I don't know if my intended use was how it should be used. Long story short, we have an e-commerce system which auto subscribes shoppers to Mailchimp if they opt-in.

The annoying thing is that a shopper can update their bio on both Woocommerce and Mailchimp (as well as when they visit in-store and update their loyalty card details on EPOS Now) - so we might have their name as something different in each place.

I was just experimenting to see if I could connect Mailchimp as a source and see what sort of data it pulls in.

My desired use case is that Grouparoo connects to all sources / destinations and keeps everything in sync. Perhaps this isn't the purpose of Grouparoo?

**Comment by andyjih** [comment]
Hi @scottybo ! That use case is absolutely something we want to solve for; we just haven't gotten to it yet. We keep our roadmap public and updated here https://github.com/orgs/grouparoo/projects/26 if you want to keep tabs. When we prioritize using Mailchimp (and others) as a Source, we'll update the roadmap accordingly. Thanks for trying Grouparoo out!
