### ISSUE TITLE
Cannot add source via Postgres App

### ISSUE THREAD

**Issue by alastairstuart** [grouparoo/grouparoo#767]
**Describe the bug**

**To Reproduce**
1. Add a Postgres App
2. Verify the number of tables in the schema is correct
3. Add a source from the app
4. Choose Postgres Table Import
5. Add a source name
6. See (valid) list of tables to choose from
7. Choose a table ('customers') 
8. See error in red toast 'Error: relation "customers" does not exist

**Expected behavior**
I should be able to add the table

**Screenshots**
![image](https://user-images.githubusercontent.com/341814/94173434-dbd06b80-fe8b-11ea-92fc-c976ddff82a3.png)

**Stack Trace**

**Environment (please complete the following information):**
 - OS: Docker default running on Heroku
 - Browser Chrome
 - Grouparoo Version v0.1.14
 - Node.js Version Docker default

**Additional context**
Db Connection seems fine -, it can list the tables just not create a source.
Schema is not 'public' could this be causing the issue?

**Comment by andyjih** [comment]
Hi there, thank you for reporting this issue! While we investigate this issue a bit more, I was wondering if you might be able to try a couple workarounds?

1. Can you try restarting your Grouparoo server? And after the server has restarted, can you try to make a source on that app?
2. If you make a new Postgres app and make sure that the `schema` option is set when you first make it, does that allow you to create a source?

Thanks!

**Comment by alastairstuart** [comment]
Thank you, restarting the server fixed the issue.

**Comment by bleonard** [comment]
Grouparoo is caching the Postgres connection to be more efficient, but we need to reconnect when the app settings change. That's why restarting works. It seems the adage about hard things in programming remain true (cache invalidation).
We will get on it soon. Thanks for the report!

**Comment by evantahler** [comment]
We've got this updated in #794.  Thanks for reporting the bug @alastairstuart!
