### ISSUE TITLE
Support SSL when connecting to the Grouparoo Postgres DB

### ISSUE THREAD

**Issue by andyjih** [grouparoo/grouparoo#882]
Non-hobby Heroku Postgres instances require SSL. Grouparoo does not currently connect using SSL to it's own database. 

https://github.com/sequelize/sequelize/issues/956#issuecomment-147745033

Thanks @alastairstuart for the report!

**Comment by andyjih** [comment]
From Al: 

"I spent some time today trying to promote the DB Grouparoo was using (it’s own, not the source DB) however I’ve bumped into yet another SSL issue.

As all non hobbyHeroku Postgres instances require SSL (unlike hobby DBs), Grouparoo cannot connect to the promoted database:

```2020-10-22T13:57:09.807217+00:00 app[web.1]: 2020-10-22T13:57:09.806Z - emerg: Exception occurred in initializer `sequelize` during load
2020-10-22T13:57:09.808132+00:00 app[web.1]: 2020-10-22T13:57:09.808Z - emerg: Error with initializer step: "initialize"
2020-10-22T13:57:09.808445+00:00 app[web.1]: 2020-10-22T13:57:09.808Z - emerg: SequelizeConnectionError: no pg_hba.conf entry for host "3.249.48.198", user "ubgqltk5rdrd7q", database "ddb0jaqiksjfud", SSL off
```

It seems there’s no SSL support here:

https://github.com/grouparoo/grouparoo/blob/master/core/api/src/config/sequelize.ts 

Heroku DATABASE_URLs do not add ?sslmode=required, so I had to manually detach the PG instance and edit the URL to include one. However this is not parsed.

How can I get Grouparoo to connect to its own DB?"

**Comment by evantahler** [comment]
Specifically on Heroku, they do not add the common flag `sslmode=require` to `process.env.DATABASE_URL`.  We also shouldn't modify `process.env.DATABASE_URL` as Heroku needs to be able to change it as they rotate database servers.  So, we need another way to tell that we should be using SSL.

https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku#ssl

**Comment by evantahler** [comment]
Since there are a whole myriad options we might need one day for SSL connections to the Grouparoo database, we probably should use additional ENV variables to control things. (certs, ssl-enabled, etc)

**Comment by evantahler** [comment]
https://github.com/grouparoo/grouparoo/pull/886 will close this Issue.  

@alastairstuart - for Heroku specifically, I'd recommend not messing with the `DATABASE_URL` they provide, but using the new `DATABASE_SSL=true` and `DATABASE_SSL_SELF_SIGNED=true` environment variables

**Comment by evantahler** [comment]
https://github.com/grouparoo/grouparoo/pull/889 will also be needed for Heroku.  Previous comment updated
